import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { logSuccess } from './utils.js';

export interface Config {
  OPENROUTER_API_KEY: string;
  DEFAULT_MODEL: string;
  DATA_COLLECTION: 'allow' | 'deny';
  PROVIDER_SORT: '' | 'price' | 'throughput' | 'latency';
}

const CONFIG_DIR = path.join(os.homedir(), '.openrouter-launch');
const CONFIG_FILE = path.join(CONFIG_DIR, 'config');

const DEFAULT_CONFIG: Config = {
  OPENROUTER_API_KEY: '',
  DEFAULT_MODEL: '',
  DATA_COLLECTION: 'deny',
  PROVIDER_SORT: ''
};

/**
 * Ensure the config directory exists with proper permissions
 */
function ensureConfigDir(): void {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  }
}

/**
 * Parse a shell-style config file
 */
function parseConfigFile(content: string): Partial<Config> {
  const config: Record<string, string> = {};

  for (const line of content.split('\n')) {
    // Skip comments and empty lines
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    // Parse KEY="value" or KEY=value
    const match = trimmed.match(/^([A-Z_]+)=["']?([^"']*)["']?$/);
    if (match) {
      config[match[1]] = match[2];
    }
  }

  return config as unknown as Partial<Config>;
}

/**
 * Load configuration from file and environment
 */
export function loadConfig(): Config {
  ensureConfigDir();

  let fileConfig: Partial<Config> = {};

  if (fs.existsSync(CONFIG_FILE)) {
    try {
      const content = fs.readFileSync(CONFIG_FILE, 'utf-8');
      fileConfig = parseConfigFile(content);
    } catch {
      // Ignore read errors
    }
  }

  // Environment variables override file config
  const envApiKey = process.env.OPENROUTER_API_KEY;
  const envModel = process.env.DEFAULT_MODEL;

  return {
    OPENROUTER_API_KEY: envApiKey || fileConfig.OPENROUTER_API_KEY || DEFAULT_CONFIG.OPENROUTER_API_KEY,
    DEFAULT_MODEL: envModel || fileConfig.DEFAULT_MODEL || DEFAULT_CONFIG.DEFAULT_MODEL,
    DATA_COLLECTION: (fileConfig.DATA_COLLECTION as Config['DATA_COLLECTION']) || DEFAULT_CONFIG.DATA_COLLECTION,
    PROVIDER_SORT: (fileConfig.PROVIDER_SORT as Config['PROVIDER_SORT']) || DEFAULT_CONFIG.PROVIDER_SORT
  };
}

/**
 * Save configuration to file
 */
export function saveConfig(config: Partial<Config>): void {
  ensureConfigDir();

  // Load existing config and merge
  const existing = loadConfig();
  const merged: Config = { ...existing, ...config };

  const content = `# openrouter-launch configuration
# Generated by openrouter-launch v1.0.0

OPENROUTER_API_KEY="${merged.OPENROUTER_API_KEY}"
DEFAULT_MODEL="${merged.DEFAULT_MODEL}"
DATA_COLLECTION="${merged.DATA_COLLECTION}"
PROVIDER_SORT="${merged.PROVIDER_SORT}"
`;

  fs.writeFileSync(CONFIG_FILE, content, { mode: 0o600 });
  logSuccess(`Configuration saved to ${CONFIG_FILE}`);
}

/**
 * Get the config directory path
 */
export function getConfigDir(): string {
  return CONFIG_DIR;
}

/**
 * Get the config file path
 */
export function getConfigFile(): string {
  return CONFIG_FILE;
}
